version: '3.8'

services:
  # Serviço do PostgreSQL
  postgres:
    image: postgres:14.3
    container_name: postgres_container
    environment:
      POSTGRES_USER: my_user    
      POSTGRES_PASSWORD: my_password  
      POSTGRES_DB: case_client       
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  # Serviço do MongoDB
  mongo:
    image: mongo:6.0
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: my_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: my_mongo_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Serviço da aplicação
  case_client:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: case_client_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres 
      - mongo
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=my_user
      - DB_PASSWORD=my_password
      - DB_NAME=case_client
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=my_mongo_user
      - MONGO_PASSWORD=my_mongo_password
      - MONGO_DB=case_client
    restart: on-failure 

volumes:
  postgres_data:
  mongo_data:
